"""corpus distillation prep (NO TRAINING).

Reads research notes + run summaries, applies a stack of quality
filters, and writes a candidate training-data JSONL plus a stats
report. **Stages only** -- this script does not touch the model and
is not an approval to train.

Filters applied (each is a hard skip, not a downweight):
  1. runs.jsonl: only `success=True` runs
  2. issues.jsonl: skip topics with > MAX_ISSUE_TOPICS
  3. ζ.1 critic verdict (if recorded): skip notes with
     `critique_severity=high` or any `internal_contradictions` entry
  4. extract_note() post-strip: skip notes that still contain
     `<tool_result>` (renderer didn't strip cleanly -- training on
     this would teach hallucinated web-style)
  5. looks_secret(): skip notes that match the secret-pattern guard
     used by memory_insert. Defense in depth -- the corpus has a
     different blast radius than memory.db.

Sources:
  - ~/.azriel/data/research/notes/*.md (autoresearch)

NOT included in this ship:
  - ~/.azriel/data/conversations.db (chat history). At time of
    writing the conversations table has 48 user-assistant turns,
    which is too thin to materially change the corpus and adds a
    different secret-leak surface (a user could have pasted
    credentials into a chat). Add as a pre-flight step
    when conversation count is materially higher AND the same
    looks_secret pass is run over each turn.

Output:
  ~/.azriel/data/synthetic/azriel_corpus.jsonl
  ~/.azriel/data/synthetic/corpus_stats.md

Run on a development machine:
    PYTHONPATH=. ~/.azriel/.venv/bin/python scripts/62_distill_corpus.py

Honest reading of the output: at current N, the corpus is staged
infrastructure for , NOT a training-ready dataset. Re-run
when (a) ε.4 issue triage shows a meaningful jump in
success-without-critique-flag runs, or (b) η pre-flight needs a
candidate corpus to point at.
"""
from __future__ import annotations

import json
import re
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

from azriel.tools.memory_insert import looks_secret

HOME = Path.home()
DATA_ROOT = HOME / ".azriel" / "data"
NOTES_DIR = DATA_ROOT / "research" / "notes"
RUNS_LOG = DATA_ROOT / "research" / "runs.jsonl"
ISSUES_LOG = DATA_ROOT / "research" / "issues.jsonl"
OUT_DIR = DATA_ROOT / "synthetic"
OUT_CORPUS = OUT_DIR / "azriel_corpus.jsonl"
OUT_STATS = OUT_DIR / "corpus_stats.md"
CONSTITUTION_PATH = HOME / ".azriel" / "AZRIEL_CONSTITUTION_SYSTEM.txt"

# Filter knobs
MIN_NOTE_CHARS = 400
MAX_ISSUE_TOPICS = 6 # > this many issues for the same topic = skip
TOOL_RESULT_PATTERN = re.compile(r"<tool_result>", re.I)


@dataclass
class CorpusStats:
    notes_total: int = 0
    notes_kept: int = 0
    skipped_no_run: int = 0
    skipped_run_failed: int = 0
    skipped_too_short: int = 0
    skipped_high_issues: int = 0
    skipped_critique_high: int = 0
    skipped_critique_contradictions: int = 0
    skipped_tool_result_bleed: int = 0
    skipped_secret: int = 0
    sample_topics: list[str] = field(default_factory=list)
    avg_chars: int = 0


def load_runs() -> dict[str, dict]:
    """Most recent run per slug -- if a topic was retried, the latest
    summary wins."""
    if not RUNS_LOG.exists():
        return {}
    by_slug = {}
    for line in RUNS_LOG.open():
        line = line.strip()
        if not line:
            continue
        try:
            r = json.loads(line)
        except Exception:
            continue
        slug = r.get("slug") or ""
        if slug:
            by_slug[slug] = r
    return by_slug


def count_issues_per_topic() -> dict[str, int]:
    if not ISSUES_LOG.exists():
        return {}
    counts = {}
    for line in ISSUES_LOG.open():
        line = line.strip()
        if not line:
            continue
        try:
            i = json.loads(line)
        except Exception:
            continue
        topic = i.get("topic") or ""
        counts[topic] = counts.get(topic, 0) + 1
    return counts


def strip_note_chrome(text: str) -> str:
    """Remove the autoresearch header (the `# topic` + metadata) from
    a saved note. Training data should be the body only."""
    # The header pattern from research.py write:
    # # <topic>\n\n_Generated by Azriel autoresearch on ...\n\n
    # _Tools fired: .../_\n\n---\n\n<body>
    parts = text.split("---", 1)
    body = parts[1] if len(parts) == 2 else text
    return body.strip()


def to_chat_record(topic: str, body: str, system_prompt: str) -> dict:
    """Render as MLX-LM chat-format with constitution as system. Body
    becomes the assistant turn; topic becomes a user-style research
    request that produces it. This is what 21_format_for_lora.py
    expects."""
    user = f"Research this topic for me, in depth: {topic}"
    return {
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user},
            {"role": "assistant", "content": body},
        ]
    }


def main() -> int:
    if not NOTES_DIR.exists():
        print(f"no notes dir at {NOTES_DIR}; nothing to distill")
        return 0
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    try:
        system_prompt = CONSTITUTION_PATH.read_text().strip()
    except Exception:
        print(f"WARN: constitution not at {CONSTITUTION_PATH}; using empty system")
        system_prompt = ""

    runs = load_runs()
    issue_counts = count_issues_per_topic()
    stats = CorpusStats()
    char_total = 0
    out_rows: list[dict] = []

    for note_path in sorted(NOTES_DIR.glob("*.md")):
        stats.notes_total += 1
        slug = note_path.stem
        run = runs.get(slug)

        if run is None:
            stats.skipped_no_run += 1
            continue
        if not run.get("success"):
            stats.skipped_run_failed += 1
            continue

        topic = run.get("topic") or slug
        if issue_counts.get(topic, 0) > MAX_ISSUE_TOPICS:
            stats.skipped_high_issues += 1
            continue

        # ζ.1 critic filters (only present on runs after the ζ.1 ship)
        if run.get("critique_severity") == "high":
            stats.skipped_critique_high += 1
            continue
        # We don't have a separate field for contradictions in run
        # summary, but issue_count >= 3 with severity=medium is a soft
        # proxy. Conservative: only filter on explicit severity=high.

        try:
            raw = note_path.read_text()
        except Exception:
            stats.skipped_no_run += 1
            continue
        body = strip_note_chrome(raw)
        if len(body) < MIN_NOTE_CHARS:
            stats.skipped_too_short += 1
            continue
        if TOOL_RESULT_PATTERN.search(body):
            stats.skipped_tool_result_bleed += 1
            continue
        if looks_secret(body):
            stats.skipped_secret += 1
            continue

        out_rows.append(to_chat_record(topic, body, system_prompt))
        stats.notes_kept += 1
        char_total += len(body)
        if len(stats.sample_topics) < 5:
            stats.sample_topics.append(topic)

    if stats.notes_kept:
        stats.avg_chars = char_total // stats.notes_kept

    # Write corpus
    with OUT_CORPUS.open("w") as f:
        for row in out_rows:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")

    # Write stats report
    lines = [
        "# Azriel Corpus -- distillation stats",
        "",
        f"Generated: {time.strftime('%Y-%m-%d %H:%M:%S')}",
        f"Source: research notes only (chat history NOT included this ship)",
        f"Output: {OUT_CORPUS}",
        "",
        "## Counts",
        "",
        f"- notes seen: {stats.notes_total}",
        f"- notes kept: **{stats.notes_kept}**",
        f"- skipped (no run record): {stats.skipped_no_run}",
        f"- skipped (run failed): {stats.skipped_run_failed}",
        f"- skipped (under {MIN_NOTE_CHARS} chars): {stats.skipped_too_short}",
        f"- skipped (issue count > {MAX_ISSUE_TOPICS}): {stats.skipped_high_issues}",
        f"- skipped (critic severity=high):{stats.skipped_critique_high}",
        f"- skipped (<tool_result> bleed): {stats.skipped_tool_result_bleed}",
        f"- skipped (secret pattern): {stats.skipped_secret}",
        "",
        f"avg chars / kept row: {stats.avg_chars}",
        "",
        "## Sample topics kept",
        "",
    ]
    for t in stats.sample_topics:
        lines.append(f"- {t}")
    if not stats.sample_topics:
        lines.append("- (none)")
    lines += [
        "",
        "## Honest read",
        "",
        f"At N={stats.notes_kept}, this corpus is staged infrastructure for",
        "(base-model swap). It is NOT a training-ready dataset.",
        "Re-run when ε.4 issue triage shows a meaningful jump in",
        "success-without-critique-flag runs, or when η pre-flight needs",
        "a candidate corpus to point at.",
        "",
        "## What we filtered FOR (not against)",
        "",
        "- runs.jsonl `success=True` (note >200 chars and no",
        " safety_misroute, per ε.1 criterion)",
        "- ζ.1 critic verdict not `severity=high` (when present)",
        "- post-strip body does not contain raw `<tool_result>` (would",
        " teach hallucinated web-content style)",
        "- looks_secret() pass (full-record check, not just the",
        " one-line summary that goes to memory.db)",
        "",
        "## What we did NOT include this ship",
        "",
        f"- ~/.azriel/data/conversations.db (chat history). At",
        " current count (~48 user-assistant turns) it would not",
        " materially change the corpus and adds a different secret-",
        " leak surface (user could have pasted credentials into a",
        " chat). Add as a pre-flight step when count is",
        " materially higher AND the same looks_secret pass runs over",
        " each turn.",
    ]
    OUT_STATS.write_text("\n".join(lines) + "\n")

    print(f"wrote {stats.notes_kept} rows to {OUT_CORPUS}")
    print(f"wrote stats to {OUT_STATS}")
    print(f"skipped: {stats.notes_total - stats.notes_kept} "
          f"(failed/short/issues/critic/bleed/secret)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
